# Copyright (c) 2015, German Aerospace Center (DLR)
# All Rights Reserved.

PROG= model1
SRCS= main.cpp Model_1.cpp ../../communication/Subscriber.cpp ../../communication/Publisher.cpp \
../../communication/Dealer.cpp
BINDIR = ../../../bin
OBJDIR = ../../../obj

include ../../../makefile.default.mk