
PROG = eventQueue
SRCS= main.cpp Queue.cpp  ../../communication/Subscriber.cpp ../../communication/Publisher.cpp \
../../communication/Dealer.cpp ../scheduler/Scheduler.cpp

include ../../makefile.default.mk