
PROG = eventQueue
SRCS= main.cpp Queue.cpp ../../communication/Subscriber.cpp ../../communication/Publisher.cpp \
../../communication/Dealer.cpp ../scheduler/Scheduler.cpp
BINDIR = ../../../bin
OBJDIR = ../../../obj

include ../../../makefile.default.mk