# Copyright (c) 2015, German Aerospace Center (DLR)
# All Rights Reserved.

PROG= model2
SRCS= main.cpp Model_2.cpp ../../communication/Subscriber.cpp ../../communication/Publisher.cpp \
../../communication/Dealer.cpp

include ../../makefile.default.mk