
PROG = simulationModel
SRCS= main.cpp SimulationModel.cpp ../communication/Subscriber.cpp ../communication/Publisher.cpp \
../communication/Dealer.cpp
BINDIR = ../../bin
OBJDIR = ../../obj

include ../../makefile.default.mk